/* eslint-disable no-console */
/**
 * sync-abis.ts
 *
 * Reads ABIs from Foundry's `out/` directory and writes a TypeScript module
 * (`frontend/lib/abis.generated.ts`) that the app imports.
 *
 * Why a script (vs. importing the JSON directly at runtime)?
 *   1. Keeps `lib/contracts.ts` strongly typed with no `any` casts.
 *   2. Lets us cherry-pick only the ABIs we ship (keeps bundle size small).
 *   3. Works identically in Next.js server components and client components —
 *      no dynamic require() pitfalls.
 *
 * Run after every `forge build`:
 *   npm run sync-abis
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const REPO_ROOT = path.resolve(__dirname, "../..");
const OUT_DIR = path.join(REPO_ROOT, "out");
const TARGET = path.join(__dirname, "../lib/abis.generated.ts");

const CONTRACTS = {
  IntentAuction: "IntentAuction.sol/IntentAuction.json",
  Executor: "Executor.sol/Executor.json",
  MockERC20: "MockERC20.sol/MockERC20.json",
  MockSwapRouter: "MockSwapRouter.sol/MockSwapRouter.json",
  MockLendingPool: "MockLendingPool.sol/MockLendingPool.json",
} as const;

type Name = keyof typeof CONTRACTS;

function readAbi(name: Name): unknown[] {
  const abiPath = path.join(OUT_DIR, CONTRACTS[name]);
  if (!fs.existsSync(abiPath)) {
    throw new Error(`Missing build artifact: ${abiPath}. Run \`forge build\` first.`);
  }
  const artifact = JSON.parse(fs.readFileSync(abiPath, "utf8"));
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`Artifact at ${abiPath} has no abi[] field.`);
  }
  return artifact.abi;
}

const abis: Record<Name, unknown[]> = Object.fromEntries(
  (Object.keys(CONTRACTS) as Name[]).map((name) => [name, readAbi(name)])
) as Record<Name, unknown[]>;

const body = `/**
 * AUTOGENERATED BY scripts/sync-abis.ts on ${new Date().toISOString()}.
 * Do not edit by hand.
 */
import type { Abi } from "viem";

export const ABIS: Record<
  "IntentAuction" | "Executor" | "MockERC20" | "MockSwapRouter" | "MockLendingPool",
  Abi
> = ${JSON.stringify(abis, null, 2)} as const;
`;

fs.writeFileSync(TARGET, body);
console.log(`Wrote ${TARGET} (${Object.keys(abis).length} ABIs)`);
