/**
 * AUTOGENERATED BY scripts/sync-abis.ts on 2026-04-21T21:40:08.132Z.
 * Do not edit by hand.
 */
import type { Abi } from "viem";

export const ABIS: Record<
  "IntentAuction" | "Executor" | "MockERC20" | "MockSwapRouter" | "MockLendingPool",
  Abi
> = {
  "IntentAuction": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "initialOwner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "DOMAIN_SEPARATOR",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "allowedTargets",
      "inputs": [
        {
          "name": "target",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "allowed",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "auctions",
      "inputs": [
        {
          "name": "intentId",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "intent",
          "type": "tuple",
          "internalType": "struct IIntentAuction.Intent",
          "components": [
            {
              "name": "user",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "tokenIn",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "amountIn",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "tokenOut",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "minAmountOut",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "maxSolverFee",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "auctionDuration",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "nonce",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "deadline",
              "type": "uint256",
              "internalType": "uint256"
            }
          ]
        },
        {
          "name": "winningBid",
          "type": "tuple",
          "internalType": "struct IIntentAuction.Bid",
          "components": [
            {
              "name": "solver",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "placedAtBlock",
              "type": "uint96",
              "internalType": "uint96"
            },
            {
              "name": "outputOffered",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "solverFee",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "target",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "executionCalldata",
              "type": "bytes",
              "internalType": "bytes"
            }
          ]
        },
        {
          "name": "auctionEndBlock",
          "type": "uint96",
          "internalType": "uint96"
        },
        {
          "name": "status",
          "type": "uint8",
          "internalType": "uint8"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "bidOnIntent",
      "inputs": [
        {
          "name": "id",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "outputOffered",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "solverFee",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "target",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "executionCalldata",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "blocksLeft",
      "inputs": [
        {
          "name": "id",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "cancelIntent",
      "inputs": [
        {
          "name": "id",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "currentNetValue",
      "inputs": [
        {
          "name": "id",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "eip712Domain",
      "inputs": [],
      "outputs": [
        {
          "name": "fields",
          "type": "bytes1",
          "internalType": "bytes1"
        },
        {
          "name": "name",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "version",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "chainId",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "verifyingContract",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "salt",
          "type": "bytes32",
          "internalType": "bytes32"
        },
        {
          "name": "extensions",
          "type": "uint256[]",
          "internalType": "uint256[]"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "executor",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "contract Executor"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "getAuction",
      "inputs": [
        {
          "name": "id",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "tuple",
          "internalType": "struct IIntentAuction.AuctionState",
          "components": [
            {
              "name": "intent",
              "type": "tuple",
              "internalType": "struct IIntentAuction.Intent",
              "components": [
                {
                  "name": "user",
                  "type": "address",
                  "internalType": "address"
                },
                {
                  "name": "tokenIn",
                  "type": "address",
                  "internalType": "address"
                },
                {
                  "name": "amountIn",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "tokenOut",
                  "type": "address",
                  "internalType": "address"
                },
                {
                  "name": "minAmountOut",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "maxSolverFee",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "auctionDuration",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "nonce",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "deadline",
                  "type": "uint256",
                  "internalType": "uint256"
                }
              ]
            },
            {
              "name": "winningBid",
              "type": "tuple",
              "internalType": "struct IIntentAuction.Bid",
              "components": [
                {
                  "name": "solver",
                  "type": "address",
                  "internalType": "address"
                },
                {
                  "name": "placedAtBlock",
                  "type": "uint96",
                  "internalType": "uint96"
                },
                {
                  "name": "outputOffered",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "solverFee",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "target",
                  "type": "address",
                  "internalType": "address"
                },
                {
                  "name": "executionCalldata",
                  "type": "bytes",
                  "internalType": "bytes"
                }
              ]
            },
            {
              "name": "auctionEndBlock",
              "type": "uint96",
              "internalType": "uint96"
            },
            {
              "name": "status",
              "type": "uint8",
              "internalType": "uint8"
            }
          ]
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "hashIntentDigest",
      "inputs": [
        {
          "name": "i",
          "type": "tuple",
          "internalType": "struct IIntentAuction.Intent",
          "components": [
            {
              "name": "user",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "tokenIn",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "amountIn",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "tokenOut",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "minAmountOut",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "maxSolverFee",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "auctionDuration",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "nonce",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "deadline",
              "type": "uint256",
              "internalType": "uint256"
            }
          ]
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "increaseNonce",
      "inputs": [],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "nonces",
      "inputs": [
        {
          "name": "user",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "nonce",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "owner",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "postIntent",
      "inputs": [
        {
          "name": "i",
          "type": "tuple",
          "internalType": "struct IIntentAuction.Intent",
          "components": [
            {
              "name": "user",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "tokenIn",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "amountIn",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "tokenOut",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "minAmountOut",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "maxSolverFee",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "auctionDuration",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "nonce",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "deadline",
              "type": "uint256",
              "internalType": "uint256"
            }
          ]
        },
        {
          "name": "sig",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "outputs": [
        {
          "name": "id",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "renounceOwnership",
      "inputs": [],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "setTargetAllowed",
      "inputs": [
        {
          "name": "target",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "allowed",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "settle",
      "inputs": [
        {
          "name": "id",
          "type": "bytes32",
          "internalType": "bytes32"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "transferOwnership",
      "inputs": [
        {
          "name": "newOwner",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "event",
      "name": "BidPlaced",
      "inputs": [
        {
          "name": "intentId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "solver",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "outputOffered",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "solverFee",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "netValueToUser",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "EIP712DomainChanged",
      "inputs": [],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "IntentCancelled",
      "inputs": [
        {
          "name": "intentId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "user",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "IntentPosted",
      "inputs": [
        {
          "name": "intentId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "user",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "tokenIn",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "tokenOut",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        },
        {
          "name": "amountIn",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "minAmountOut",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "auctionEndBlock",
          "type": "uint96",
          "indexed": false,
          "internalType": "uint96"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "OwnershipTransferred",
      "inputs": [
        {
          "name": "previousOwner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "newOwner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "Settled",
      "inputs": [
        {
          "name": "intentId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "solver",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "delivered",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "solverFee",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "userReceives",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "TargetAllowed",
      "inputs": [
        {
          "name": "target",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "allowed",
          "type": "bool",
          "indexed": false,
          "internalType": "bool"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "AddressEmptyCode",
      "inputs": [
        {
          "name": "target",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "AddressInsufficientBalance",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "AuctionEnded",
      "inputs": []
    },
    {
      "type": "error",
      "name": "AuctionNotEnded",
      "inputs": []
    },
    {
      "type": "error",
      "name": "BadNonce",
      "inputs": [
        {
          "name": "expected",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "got",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "BadSignature",
      "inputs": []
    },
    {
      "type": "error",
      "name": "BidBelowMin",
      "inputs": []
    },
    {
      "type": "error",
      "name": "BidNotAnImprovement",
      "inputs": []
    },
    {
      "type": "error",
      "name": "DeliveredLessThanCommitted",
      "inputs": [
        {
          "name": "committed",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "delivered",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "FailedInnerCall",
      "inputs": []
    },
    {
      "type": "error",
      "name": "FeeExceedsMax",
      "inputs": []
    },
    {
      "type": "error",
      "name": "FeeExceedsOutput",
      "inputs": []
    },
    {
      "type": "error",
      "name": "IntentAlreadyPosted",
      "inputs": []
    },
    {
      "type": "error",
      "name": "IntentExpired",
      "inputs": []
    },
    {
      "type": "error",
      "name": "IntentNotActive",
      "inputs": []
    },
    {
      "type": "error",
      "name": "IntentNotSettleable",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidAddress",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidAmount",
      "inputs": []
    },
    {
      "type": "error",
      "name": "InvalidShortString",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NotIntentOwner",
      "inputs": []
    },
    {
      "type": "error",
      "name": "OwnableInvalidOwner",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "OwnableUnauthorizedAccount",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "ReentrancyGuardReentrantCall",
      "inputs": []
    },
    {
      "type": "error",
      "name": "SafeERC20FailedOperation",
      "inputs": [
        {
          "name": "token",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "SelfCallForbidden",
      "inputs": []
    },
    {
      "type": "error",
      "name": "StringTooLong",
      "inputs": [
        {
          "name": "str",
          "type": "string",
          "internalType": "string"
        }
      ]
    },
    {
      "type": "error",
      "name": "TargetNotAllowed",
      "inputs": [
        {
          "name": "target",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "UnauthorizedCaller",
      "inputs": []
    }
  ],
  "Executor": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "auction_",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "auction",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "execute",
      "inputs": [
        {
          "name": "p",
          "type": "tuple",
          "internalType": "struct IExecutor.ExecutionParams",
          "components": [
            {
              "name": "intentId",
              "type": "bytes32",
              "internalType": "bytes32"
            },
            {
              "name": "solver",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "target",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "data",
              "type": "bytes",
              "internalType": "bytes"
            },
            {
              "name": "tokenIn",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "amountIn",
              "type": "uint256",
              "internalType": "uint256"
            },
            {
              "name": "tokenOut",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "user",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "minDeliver",
              "type": "uint256",
              "internalType": "uint256"
            }
          ]
        }
      ],
      "outputs": [
        {
          "name": "delivered",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "executeWithFee",
      "inputs": [
        {
          "name": "p",
          "type": "tuple",
          "internalType": "struct Executor.FeeSplitParams",
          "components": [
            {
              "name": "base",
              "type": "tuple",
              "internalType": "struct IExecutor.ExecutionParams",
              "components": [
                {
                  "name": "intentId",
                  "type": "bytes32",
                  "internalType": "bytes32"
                },
                {
                  "name": "solver",
                  "type": "address",
                  "internalType": "address"
                },
                {
                  "name": "target",
                  "type": "address",
                  "internalType": "address"
                },
                {
                  "name": "data",
                  "type": "bytes",
                  "internalType": "bytes"
                },
                {
                  "name": "tokenIn",
                  "type": "address",
                  "internalType": "address"
                },
                {
                  "name": "amountIn",
                  "type": "uint256",
                  "internalType": "uint256"
                },
                {
                  "name": "tokenOut",
                  "type": "address",
                  "internalType": "address"
                },
                {
                  "name": "user",
                  "type": "address",
                  "internalType": "address"
                },
                {
                  "name": "minDeliver",
                  "type": "uint256",
                  "internalType": "uint256"
                }
              ]
            },
            {
              "name": "solverFee",
              "type": "uint256",
              "internalType": "uint256"
            }
          ]
        }
      ],
      "outputs": [
        {
          "name": "delivered",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "event",
      "name": "Executed",
      "inputs": [
        {
          "name": "intentId",
          "type": "bytes32",
          "indexed": true,
          "internalType": "bytes32"
        },
        {
          "name": "solver",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "target",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "user",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        },
        {
          "name": "amountIn",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "delivered",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "AddressEmptyCode",
      "inputs": [
        {
          "name": "target",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "AddressInsufficientBalance",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "DeliveredLessThanCommitted",
      "inputs": [
        {
          "name": "committed",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "delivered",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "FailedInnerCall",
      "inputs": []
    },
    {
      "type": "error",
      "name": "FeeExceedsOutput",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NotAuction",
      "inputs": []
    },
    {
      "type": "error",
      "name": "ReentrancyGuardReentrantCall",
      "inputs": []
    },
    {
      "type": "error",
      "name": "SafeERC20FailedOperation",
      "inputs": [
        {
          "name": "token",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "ZeroAddress",
      "inputs": []
    }
  ],
  "MockERC20": [
    {
      "type": "constructor",
      "inputs": [
        {
          "name": "name_",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "symbol_",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "decimals_",
          "type": "uint8",
          "internalType": "uint8"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "allowance",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "spender",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "approve",
      "inputs": [
        {
          "name": "spender",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "value",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "balanceOf",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "decimals",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint8",
          "internalType": "uint8"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "mint",
      "inputs": [
        {
          "name": "to",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "name",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "string",
          "internalType": "string"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "symbol",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "string",
          "internalType": "string"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "totalSupply",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "transfer",
      "inputs": [
        {
          "name": "to",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "value",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "transferFrom",
      "inputs": [
        {
          "name": "from",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "to",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "value",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "bool",
          "internalType": "bool"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "event",
      "name": "Approval",
      "inputs": [
        {
          "name": "owner",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "spender",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "value",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "Transfer",
      "inputs": [
        {
          "name": "from",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "to",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "value",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "ERC20InsufficientAllowance",
      "inputs": [
        {
          "name": "spender",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "allowance",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "needed",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "ERC20InsufficientBalance",
      "inputs": [
        {
          "name": "sender",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "balance",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "needed",
          "type": "uint256",
          "internalType": "uint256"
        }
      ]
    },
    {
      "type": "error",
      "name": "ERC20InvalidApprover",
      "inputs": [
        {
          "name": "approver",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "ERC20InvalidReceiver",
      "inputs": [
        {
          "name": "receiver",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "ERC20InvalidSender",
      "inputs": [
        {
          "name": "sender",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "ERC20InvalidSpender",
      "inputs": [
        {
          "name": "spender",
          "type": "address",
          "internalType": "address"
        }
      ]
    }
  ],
  "MockSwapRouter": [
    {
      "type": "constructor",
      "inputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "PRICE_SCALE",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "admin",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "quote",
      "inputs": [
        {
          "name": "tokenIn",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "tokenOut",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "amountIn",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [
        {
          "name": "amountOut",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "rates",
      "inputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "setRate",
      "inputs": [
        {
          "name": "tokenIn",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "tokenOut",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "rate",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "swap",
      "inputs": [
        {
          "name": "tokenIn",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "tokenOut",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "amountIn",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "recipient",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "amountOut",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "nonpayable"
    },
    {
      "type": "event",
      "name": "PriceSet",
      "inputs": [
        {
          "name": "tokenIn",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "tokenOut",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "rate",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "Swapped",
      "inputs": [
        {
          "name": "caller",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "tokenIn",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "tokenOut",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "amountIn",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "amountOut",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        },
        {
          "name": "recipient",
          "type": "address",
          "indexed": false,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "AddressEmptyCode",
      "inputs": [
        {
          "name": "target",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "AddressInsufficientBalance",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "FailedInnerCall",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NoPrice",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NotAdmin",
      "inputs": []
    },
    {
      "type": "error",
      "name": "SafeERC20FailedOperation",
      "inputs": [
        {
          "name": "token",
          "type": "address",
          "internalType": "address"
        }
      ]
    }
  ],
  "MockLendingPool": [
    {
      "type": "constructor",
      "inputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "aTokens",
      "inputs": [
        {
          "name": "underlying",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [
        {
          "name": "aToken",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "admin",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "address",
          "internalType": "address"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "deposit",
      "inputs": [
        {
          "name": "asset",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "onBehalfOf",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "setAToken",
      "inputs": [
        {
          "name": "underlying",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "aToken",
          "type": "address",
          "internalType": "address"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "event",
      "name": "ATokenSet",
      "inputs": [
        {
          "name": "underlying",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "aToken",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        }
      ],
      "anonymous": false
    },
    {
      "type": "event",
      "name": "Deposited",
      "inputs": [
        {
          "name": "caller",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "onBehalfOf",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "asset",
          "type": "address",
          "indexed": true,
          "internalType": "address"
        },
        {
          "name": "amount",
          "type": "uint256",
          "indexed": false,
          "internalType": "uint256"
        }
      ],
      "anonymous": false
    },
    {
      "type": "error",
      "name": "AddressEmptyCode",
      "inputs": [
        {
          "name": "target",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "AddressInsufficientBalance",
      "inputs": [
        {
          "name": "account",
          "type": "address",
          "internalType": "address"
        }
      ]
    },
    {
      "type": "error",
      "name": "FailedInnerCall",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NoAToken",
      "inputs": []
    },
    {
      "type": "error",
      "name": "NotAdmin",
      "inputs": []
    },
    {
      "type": "error",
      "name": "SafeERC20FailedOperation",
      "inputs": [
        {
          "name": "token",
          "type": "address",
          "internalType": "address"
        }
      ]
    }
  ]
} as const;
